<a href="https://colab.research.google.com/github/jayanth2005sai-ship-it/ML_LAB_2026-2027/blob/main/lab2(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]
arr = np.array(lista)
print(arr)

[1 2 3 4]


In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [9]:
print(array1.dtype)

int64


In [10]:
print(array1.ndim)

3


In [12]:
print(array1.shape)

(2, 3, 4)


In [13]:
print(array1.size)

24


In [14]:
print(array1.data)

In [16]:
print(array1[0,2])

[ 9 10 11 12]


In [17]:
median = np.median(array1)

print(median)

12.5


In [20]:
mean_marks = np.mean(array1)

print(mean_marks)

12.5


In [21]:
std_marks = np.std(array1)
print(std_marks)

6.922186552431729


In [22]:
std_marks = np.percentile(array1,50)
print(std_marks)

12.5


In [23]:
std_marks = np.min(array1)
print(std_marks)

1


In [24]:
std_marks = np.max(array1)
print(std_marks)

24
