<a href="https://colab.research.google.com/github/jayanth2005sai-ship-it/ML_LAB_2026-2027/blob/main/lab2(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]
arr = np.array(lista)
print(arr)

[1 2 3 4]


In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [9]:
print(array1.dtype)

int64


In [10]:
print(array1.ndim)

3


In [12]:
print(array1.shape)

(2, 3, 4)


In [13]:
print(array1.size)

24


In [14]:
print(array1.data)

In [16]:
print(array1[0,2])

[ 9 10 11 12]


In [17]:
median = np.median(array1)

print(median)

12.5


In [20]:
mean_marks = np.mean(array1)

print(mean_marks)

12.5


In [21]:
std_marks = np.std(array1)
print(std_marks)

6.922186552431729


In [22]:
std_marks = np.percentile(array1,50)
print(std_marks)

12.5


In [23]:
std_marks = np.min(array1)
print(std_marks)

1


In [24]:
std_marks = np.max(array1)
print(std_marks)

24


In [25]:

import numpy as np
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([6,7,8])
z = np.add(x,y)
print("Addition of x and y:\n", z)
z = np.subtract(x,y)
print("Subtraction of y from x:\n", z)
z = np.multiply(x,y)
print("Element-wise multiplication of x and y:\n", z)

Addition of x and y:
 [[ 7  9 11]
 [ 9 11 13]]
Subtraction of y from x:
 [[-5 -5 -5]
 [-3 -3 -3]]
Element-wise multiplication of x and y:
 [[ 6 14 24]
 [18 28 40]]


In [26]:
import numpy as np

my_array = np.array([1,2,3,4])
print("my_array before appending:", my_array)
new_array = np.append(my_array, [7, 8, 9, 10])
print("new_array:", new_array)
print("my_array after appending:", my_array)


my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]
my_array after appending: [1 2 3 4]


In [27]:

import numpy as np

my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print("my_2d_array before appending:\n", my_2d_array)
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)
print("new_2d_array:\n", new_2d_array)
print("my_2d_array after appending:\n", my_2d_array)

my_2d_array before appending:
 [[1 2 3 4]
 [5 6 7 8]]
new_2d_array:
 [[1 2 3 4 7]
 [5 6 7 8 8]]
my_2d_array after appending:
 [[1 2 3 4]
 [5 6 7 8]]


In [28]:
import numpy as np
my_array = np.array([1,2,3,4])
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
np.insert(my_array, 1, 5)
np.delete(my_array,[1])

array([1, 3, 4])